name: GitHub Build
on: [push]
jobs:
  BuildProject:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt-openj9'
      - name: Install Maven
        run: sudo apt install maven -y
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build Project
        run: mvn clean install
        
