name: GitHub Build
on: [push]
jobs:
  BuildProject:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt remove java -y
      - name: Install Java
        run: sudo apt install openjdk-21-jdk
      - name: Install Maven
        run: sudo apt install maven -y
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build Project
        run: mvn clean install
        
